# Generated by Django 3.1.2 on 2020-10-13 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Floor', models.IntegerField()),
                ('No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(default=datetime.time(9, 0))),
                ('Duration', models.IntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeetingAllocation.room')),
            ],
        ),
    ]
