# Generated by Django 3.1.2 on 2020-10-13 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingAllocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeeting',
            name='Duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meeeting',
            name='Time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
